modLoader = "javafml"
loaderVersion="[1,)"
license="${license}"
showAsResourcePack=false

issueTrackerURL = "https://github.com/${github}/Combat-Effects/issues"

[[mods]]
modId="${id}"
version="${modversion}"
displayName="${display_name}"
authors="${author}"
description="${description}"
logoFile="assets/${namespace}/logo.png"
displayURL = "https://github.com/${github}/Combat-Effects"

[[mixins]]
config = "${id}.mixins.json"

[[dependencies."${id}"]]
modId="minecraft"
mandatory=true
versionRange="${mc}"
ordering="NONE"
side="BOTH"

[[dependencies."${id}"]]
modId="necronomicon"
mandatory=true
versionRange=">=1.6.0"
ordering="NONE"
side="BOTH"